# .github/workflows/main.yml
name: CI Pipeline

# Trigger on push to main or any pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip' # Caches dependencies to make runs faster

    # 3. Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest ruff # Install test tools

    # 4. Lint (Quality Control)
    # This checks for syntax errors or unused imports
    - name: Lint with Ruff
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        ruff check . --select=E9,F63,F7,F82 --target-version=py310

    # 5. Test (Reliability)
    # Runs the test_app.py file we just made
    - name: Run Tests
      run: |
        pytest tests/